name: Docker
on:
  push:
    branches:
      - master
      - test-e2e-ci
    tags:
      - "v?[0-9]+.[0-9]+.[0-9]+"
      - "v?[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+"
      - "v?[0-9]+.[0-9]+.[0-9]+-dev.[0-9]+"
  pull_request:

env:
  PLATFORMS: linux/amd64
jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Determine tag or commit
        uses: haya14busa/action-cond@v1
        id: refortag
        with:
          cond: ${{ startsWith(github.ref, 'refs/tags/') }}
          if_true: ${{ github.ref }}
          if_false: latest
      - name: Determine image tag
        id: imagetag
        run: echo "value=${TAG_OR_BRANCH##*/}" >> $GITHUB_OUTPUT
        env:
          TAG_OR_BRANCH: ${{ steps.refortag.outputs.value }}
      - name: Build and cache kafka-operator
        uses: docker/build-push-action@v3
        with:
          tags: ghcr.io/banzaicloud/kafka-operator:${{ steps.imagetag.outputs.value }}
          file: Dockerfile
          platforms: ${{ env.PLATFORMS }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          outputs: type=docker,dest=/tmp/kafka-operator-${{ steps.imagetag.outputs.value }}.tar
        if: github.event_name == 'pull_request' || github.ref_name == 'test-e2e-ci'
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: kafka-operator-${{ steps.imagetag.outputs.value }}
          path: /tmp/kafka-operator-${{ steps.imagetag.outputs.value }}.tar
        if: github.event_name == 'pull_request' || github.ref_name == 'test-e2e-ci'
      - name: run e2e test
        uses: ./.github/workflows/e2e-test.yaml
        with:
          kafka-operator-image-artifact: /tmp/kafka-operator-${{ steps.imagetag.outputs.value }}.tar
          kafka-operator-image-name: ghcr.io/banzaicloud/kafka-operator:${{ steps.imagetag.outputs.value }}
        if: github.event_name == 'pull_request' || github.ref_name == 'test-e2e-ci'
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
        if: github.event_name != 'pull_request' && github.ref_name != 'test-e2e-ci'
      - name: Build and push kafka-operator
        uses: docker/build-push-action@v3
        with:
          tags: ghcr.io/banzaicloud/kafka-operator:${{ steps.imagetag.outputs.value }}
          file: Dockerfile
          platforms: ${{ env.PLATFORMS }}
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
        if: github.event_name != 'pull_request' && github.ref_name != 'test-e2e-ci'
