name: e2e-test
on:
  workflow_call:
    inputs:
      kafka-operator-image-artifact:
        required: true
        type: string
      kafka-operator-image-name:
        required: true
        type: string
jobs:
  e2e-basic:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - v1.25.2
          - v1.24.6
          - v1.23.12
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - uses: engineerd/setup-kind@v0.5.0
        with:
          version: v0.13.0
          image: kindest/node:${{ matrix.image }}
          config: test/kind_config.yaml
      - name: Check kind cluster
        run: |
          kubectl version
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.kafka-operator-image-artifact }}
          path: /tmp
      - name: Load image
        run: |
          kind load image-archive /tmp/${{ inputs.kafka-operator-image-artifact }}.tar
      - name: run tests
        run: |
          go test -v
        working-directory: test/e2e


